# Generated by Django 2.2 on 2019-04-27 14:54

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0003_auto_20181117_2328_squashed_0004_auto_20190227_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('djstripe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id', djstripe.fields.StripeIdField(max_length=255, unique=True)),
                ('livemode', models.NullBooleanField(default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.')),
                ('created', djstripe.fields.StripeDateTimeField(blank=True, help_text='The datetime this object was created in stripe.', null=True)),
                ('metadata', djstripe.fields.JSONField(blank=True, help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this object.', null=True)),
                ('djstripe_created', models.DateTimeField(auto_now_add=True)),
                ('djstripe_updated', models.DateTimeField(auto_now=True)),
                ('billing_details', djstripe.fields.JSONField(help_text='Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.')),
                ('card', djstripe.fields.JSONField(help_text='If this is a card PaymentMethod, this hash contains details about the card.')),
                ('card_present', djstripe.fields.JSONField(help_text='If this is an card_present PaymentMethod, this hash contains details about the Card Present payment method.')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='djstripe.Customer')),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
